insert into public.properties (
  id,
  title,
  type,
  price,
  location,
  size,
  plot_area,
  usable_area,
  built_up_area,
  layout,
  short_description,
  description,
  image,
  gallery,
  matterport_url,
  map_url,
  features,
  published
) values (
  'prodej-rodinny-dum-hermanice-v-podjestedi',
  'Rodinný dům se zahradou v Heřmanicích v Podještědí',
  'prodej',
  '25 000 000 Kč',
  'Jablonné v Podještědí - Heřmanice v Podještědí',
  '350 m²',
  '3 559 m²',
  '350 m²',
  '421 m²',
  '5 a více pokojů, rodinný dům',
  'Reprezentativní rodinný dům po rekonstrukci s velkým pozemkem, zahradou, garáží a sklepem v klidné lokalitě Lužických hor.',
  'Nabízíme prostorný rodinný dům v Heřmanicích v Podještědí, který kombinuje velkorysé bydlení, rozsáhlý pozemek a příjemné soukromí v podhůří Lužických hor. Dům prošel rekonstrukcí a nabízí několik obytných místností, praktické zázemí, sklepní prostory, garáž a dostatek místa pro parkování. Díky velké zahradě a klidnému okolí je nemovitost vhodná pro rodinné bydlení, vícegenerační využití i reprezentativní rekreační zázemí.',
  'https://d18-a.sdn.cz/d_18/c_img_QM_K5/AByB3ms.jpeg?fl=res,2000,2000,1%7Cshr,,20%7Cjpg,90',
  array[
    'https://d18-a.sdn.cz/d_18/c_img_QM_K5/AByB3ms.jpeg?fl=res,2000,2000,1%7Cshr,,20%7Cjpg,90',
    'https://d18-a.sdn.cz/d_18/c_img_QJ_Jw/bC6EBHB.jpeg?fl=res,2000,2000,1%7Cshr,,20%7Cjpg,90',
    'https://d18-a.sdn.cz/d_18/c_img_QO_K5/DjSB3mm.jpeg?fl=res,2000,2000,1%7Cshr,,20%7Cjpg,90',
    'https://d18-a.sdn.cz/d_18/c_img_QP_J9/j2LB3mo.jpeg?fl=res,2000,2000,1%7Cshr,,20%7Cjpg,90',
    'https://d18-a.sdn.cz/d_18/c_img_QP_J9/l31B3mq.jpeg?fl=res,2000,2000,1%7Cshr,,20%7Cjpg,90'
  ],
  '',
  'Jablonné v Podještědí - Heřmanice v Podještědí',
  array[
    'Sklep',
    'Garáž',
    'Parkovací stání',
    'Zahrada',
    'Tepelné čerpadlo',
    'Vlastní studna',
    'Septik',
    'Po rekonstrukci',
    'K nastěhování ihned'
  ],
  true
) on conflict (id) do update set
  title = excluded.title,
  type = excluded.type,
  price = excluded.price,
  location = excluded.location,
  size = excluded.size,
  plot_area = excluded.plot_area,
  usable_area = excluded.usable_area,
  built_up_area = excluded.built_up_area,
  layout = excluded.layout,
  short_description = excluded.short_description,
  description = excluded.description,
  image = excluded.image,
  gallery = excluded.gallery,
  matterport_url = excluded.matterport_url,
  map_url = excluded.map_url,
  features = excluded.features,
  published = excluded.published;
