insert into public.properties (
  id,
  title,
  type,
  price,
  location,
  size,
  plot_area,
  usable_area,
  built_up_area,
  layout,
  short_description,
  description,
  image,
  gallery,
  matterport_url,
  map_url,
  features,
  published
) values (
  'prodej-rodinny-dum-hermanice-v-podjestedi',
  'Rodinný dům se zahradou v Heřmanicích v Podještědí',
  'prodej',
  '25 000 000 Kč',
  'Jablonné v Podještědí - Heřmanice v Podještědí',
  '350 m²',
  '3 559 m²',
  '350 m²',
  '421 m²',
  '7+kk, rodinný dům',
  'Velkorysý rodinný dům 7+kk po rozsáhlé rekonstrukci s velkým pozemkem, zahradou, garáží, sklepem a vlastním rybníkem.',
  'Nabízíme reprezentativní rodinný dům v Jablonném v Podještědí, v klidné části obklopené zelení a krajinou Lužických hor. Původní stavba z roku 1924 prošla citlivou rozsáhlou rekonstrukcí, která zachovala charakter domu a současně doplnila komfort moderního bydlení. Dispozice 7+kk poskytuje velkorysý prostor pro rodinu, vícegenerační bydlení i kombinaci soukromého bydlení s pracovním zázemím. V přízemí navazuje obytná část na kuchyň a jídelnu, dům nabízí několik ložnic, koupelny, technické zázemí, úložné prostory a praktický sklep o ploše přibližně 45 m². Součástí rekonstrukce byly mimo jiné rozvody, střecha, zateplení, okna s trojskly a hydroizolace. O vytápění se stará tepelné čerpadlo doplněné kachlovými kamny, která podtrhují atmosféru domu. Pozemek o výměře 3 559 m² nabízí upravenou zahradu, dostatek soukromí, venkovní posezení, parkování, garáž a vlastní rybník. Díky své poloze je nemovitost vhodná pro trvalé bydlení i jako nadstandardní venkovské zázemí s rychlou dostupností služeb v okolí.',
  'https://svoboda-and-williams.b-cdn.net/933100/99971660.webp?width=1680',
  array[
    'https://svoboda-and-williams.b-cdn.net/933100/99971660.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933101/99971680.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933102/99971674.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933103/99971682.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933104/99971646.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933105/99971648.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933106/99971694.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933107/99971686.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933108/99971706.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933109/99971690.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933110/99971716.webp?width=1680',
    'https://svoboda-and-williams.b-cdn.net/933111/99971702.webp?width=1680'
  ],
  '',
  'Jablonné v Podještědí - Heřmanice v Podještědí',
  array[
    'Sklep',
    'Garáž',
    'Parkovací stání',
    'Zahrada',
    'Tepelné čerpadlo',
    'Vlastní studna',
    'Septik',
    'Kachlová kamna',
    'Vlastní rybník',
    'Po rekonstrukci',
    'K nastěhování ihned'
  ],
  true
) on conflict (id) do update set
  title = excluded.title,
  type = excluded.type,
  price = excluded.price,
  location = excluded.location,
  size = excluded.size,
  plot_area = excluded.plot_area,
  usable_area = excluded.usable_area,
  built_up_area = excluded.built_up_area,
  layout = excluded.layout,
  short_description = excluded.short_description,
  description = excluded.description,
  image = excluded.image,
  gallery = excluded.gallery,
  matterport_url = excluded.matterport_url,
  map_url = excluded.map_url,
  features = excluded.features,
  published = excluded.published;
